# Kaggle kernel: optimized candidate generation (src/fast_normalization.py + src/fast_blocking.py)
# on the real train data, with candidate recall against train_ground_truth.tsv.
# Generated by kaggle/build_kernel.py -- edit the template, not kernel/run_blocking.py.
import base64, glob, json, logging, os, subprocess, sys, time

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "sparse_dot_topn", "jellyfish", "unidecode", "polars", "bm25s"], check=False)

SRC = __SRC_FILES__
os.makedirs("src", exist_ok=True)
for name, b64 in SRC.items():
    with open(os.path.join("src", name), "wb") as f:
        f.write(base64.b64decode(b64))
sys.path.insert(0, os.getcwd())

import pandas as pd
import polars as pl
from src.fast_normalization import normalize_sources
from src.fast_blocking import BlockingConfig, build_candidate_pool

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s", stream=sys.stdout)

def find(name):
    hits = glob.glob(f"/kaggle/input/**/{name}", recursive=True)
    if not hits:
        raise FileNotFoundError(name)
    return hits[0]

SPLIT = os.environ.get("SPLIT", "train")
t0 = time.time()
stages = {}
s1, s2, s3 = (pd.read_csv(find(f"{SPLIT}_source{i}.tsv"), sep="\t") for i in (1, 2, 3))
print(f"loaded S1={len(s1):,} S2={len(s2):,} S3={len(s3):,} cols={list(s1.columns)}", flush=True)
stages["load_s"] = time.time() - t0

t = time.time()
s1n, s2n, s3n = normalize_sources([s1, s2, s3], joint_thresholds=True)
del s1, s2, s3
stages["normalize_s"] = time.time() - t
print(f"normalized in {stages['normalize_s']:.1f}s", flush=True)

t = time.time()
cfg = BlockingConfig(top_k=7, include_s2_s3=False)
pool = build_candidate_pool(s1n, s2n, s3n, cfg)
stages["blocking_s"] = time.time() - t
print(f"candidate pool: {pool.height:,} pairs in {stages['blocking_s']:.1f}s", flush=True)
pool.write_parquet(f"/kaggle/working/candidate_pool_{SPLIT}.parquet")

report = {"split": SPLIT, "n_s1": len(s1n), "n_s2": len(s2n), "n_s3": len(s3n),
          "candidate_pairs": pool.height, **{k: round(v, 1) for k, v in stages.items()}}

gt_files = glob.glob(f"/kaggle/input/**/{SPLIT}_ground_truth.tsv", recursive=True)
if gt_files:
    gt = pl.read_csv(gt_files[0], separator="\t", infer_schema_length=0)
    tp = (gt.drop_nulls("matched_entity_ids")
            .with_columns(pl.col("matched_entity_ids").str.split(","))
            .explode("matched_entity_ids")
            .select(pl.col("source1_entity_id").str.strip_chars().alias("a"),
                    pl.col("matched_entity_ids").str.strip_chars().alias("b"))
            .filter(pl.col("b") != "")
            .select(pl.min_horizontal("a", "b").alias("u"), pl.max_horizontal("a", "b").alias("v"))
            .unique())
    canon = (pool.select(pl.min_horizontal("entity_A", "entity_B").alias("u"),
                         pl.max_horizontal("entity_A", "entity_B").alias("v"),
                         "bm25_text_score", "bm25_phonetic_score", "geo_ngram_score")
                 .group_by("u", "v").agg(pl.all().max()))
    found = tp.join(canon, on=["u", "v"], how="inner")
    n = tp.height
    report.update({
        "true_pairs": n,
        "recall": found.height / n,
        "recall_text_signal": found.filter(pl.col("bm25_text_score") > 0).height / n,
        "recall_phonetic_signal": found.filter(pl.col("bm25_phonetic_score") > 0).height / n,
        "recall_geo_signal": found.filter(pl.col("geo_ngram_score") > 0).height / n,
        "pairs_per_s1": pool.height / report["n_s1"],
    })

report["total_s"] = round(time.time() - t0, 1)
print(json.dumps(report, indent=2))
with open("/kaggle/working/report.json", "w") as f:
    json.dump(report, f, indent=2)
